name = "AbInitioSoftware"
uuid = "bd21691c-901c-41c3-939b-9c02ec4395ba"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CrystallographyBase = "93b1d1cd-a8ea-4aa5-adb1-b2407ea0ba8d"

[compat]
CrystallographyBase = "0.10"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
